implementing the conversion from polar coordinates to rectangular coordinates in the star catalog using pandas

1) initialization

In [2]:
import pandas as pd
import numpy as np
astroTable = pd.read_csv('/home/user/datafile/hygdata_v3.csv', index_col='id')

In [4]:
#pd.options.display.max_rows = 999
#pd.options.display.max_columns = 500
astroTable # view the dataframe

,hip,hd,hr,gl,bf,proper,ra,dec,dist,pmra,pmdec,rv,mag,absmag,spect,ci,x,y,z,vx,vy,vz,rarad,decrad,pmrarad,pmdecrad,bayer,flam,con,comp,comp_primary,base,lum,var,var_min,var_max
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,NaN,NaN,NaN,NaN,NaN,Sol,0.000000,0.000000,0.0000,0.00,0.00,0.0,-26.70,4.850,G2V,0.656,0.000005,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,NaN,NaN,NaN,1,0,NaN,1.000000,NaN,NaN,NaN
1,1.0,224700.0,NaN,NaN,NaN,NaN,0.000060,1.089009,219.7802,-5.20,-1.88,0.0,9.10,2.390,F5,0.482,219.740502,0.003449,4.177065,4.000000e-08,-0.000006,-2.000000e-06,0.000016,0.019007,-2.521031e-08,-9.114497e-09,NaN,NaN,NaN,1,1,NaN,9.638290,NaN,NaN,NaN
2,2.0,224690.0,NaN,NaN,NaN,NaN,0.000283,-19.498840,47.9616,181.21,-0.93,0.0,9.27,5.866,K3V,0.999,45.210918,0.003365,-16.008996,-7.000000e-08,0.000042,-2.000000e-07,0.000074,-0.340319,8.785309e-07,-4.508767e-09,NaN,NaN,NaN,1,2,NaN,0.392283,NaN,NaN,NaN
3,3.0,224699.0,NaN,NaN,NaN,NaN,0.000335,38.859279,442.4779,5.24,-2.91,0.0,6.61,-1.619,B9,-0.019,344.552785,0.030213,277.614965,3.920000e-06,0.000011,-4.860000e-06,0.000088,0.678222,2.540424e-08,-1.410808e-08,NaN,NaN,NaN,1,3,NaN,386.901132,NaN,NaN,NaN
4,4.0,224707.0,NaN,NaN,NaN,NaN,0.000569,-51.893546,134.2282,62.85,0.16,0.0,8.06,2.421,F0V,0.370,82.835513,0.012476,-105.619540,8.000000e-08,0.000041,6.000000e-08,0.000149,-0.905713,3.047054e-07,7.757010e-10,NaN,NaN,NaN,1,4,NaN,9.366989,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119611,NaN,NaN,NaN,NN 4381,NaN,NaN,23.963895,38.629391,16.9492,-162.63,-162.63,0.0,12.64,11.494,m,NaN,13.240128,-0.125297,10.581054,8.220000e-06,-0.000013,-1.044000e-05,6.273733,0.674210,-7.884525e-07,-7.884719e-07,NaN,NaN,NaN,1,119611,NaN,0.002200,NaN,NaN,NaN
119612,NaN,NaN,NaN,NN 4385,NaN,NaN,23.996567,47.762093,16.7224,864.68,-210.78,0.0,16.10,14.984,m,1.870,11.240971,-0.008954,12.380596,1.273000e-05,0.000070,-1.149000e-05,6.282287,0.833606,4.192087e-06,-1.021915e-06,NaN,NaN,NaN,1,119612,NaN,0.000088,NaN,NaN,NaN
119613,NaN,NaN,NaN,NN 4386,NaN,NaN,23.996218,-44.067905,18.5185,-18.83,269.34,0.0,12.82,11.482,M7,1.640,13.305832,-0.013199,-12.879810,1.682000e-05,-0.000002,1.737000e-05,6.282195,-0.769130,-9.129042e-08,1.305807e-06,NaN,NaN,NaN,1,119613,NaN,0.002224,NaN,NaN,NaN
119614,NaN,NaN,NaN,NN 4387,NaN,NaN,23.997386,-34.111986,12.8205,715.88,-624.51,0.0,12.80,12.260,M4,NaN,10.614642,-0.006882,-7.189893,-2.172000e-05,0.000045,-3.214000e-05,6.282501,-0.595366,3.470684e-06,-3.027691e-06,NaN,NaN,NaN,1,119614,NaN,0.001086,NaN,NaN,NaN
119615,NaN,NaN,NaN,Gl 915,NaN,NaN,0.036059,-43.165974,7.8003,612.44,-673.06,0.0,13.05,13.589,DA5,0.070,5.689088,0.054021,-5.336296,-1.762000e-05,0.000023,-1.857000e-05,0.009440,-0.753388,2.969193e-06,-3.263106e-06,NaN,NaN,NaN,1,119615,NaN,0.000319,NaN,NaN,NaN

In [5]:
polarCoor, rectCoor = pd.DataFrame(), pd.DataFrame() # create 2 dataframes to implement the solution

2. calculate

In [6]:
''' note that pandas makes use of column labels, 
    which is more intuitive to researchers working with datasets than column indices
    note also that we populate the empty polarCoor dataframe with the results of our vectorized operations.
'''
polarCoor['ra'] = np.deg2rad(15 * astroTable['ra'])
polarCoor['dec'] = np.deg2rad(astroTable['dec'])
polarCoor['r'] = astroTable['dist']

In [7]:
polarCoor # view the dataframe

              ra       dec         r
id
0       0.000000  0.000000    0.0000
1       0.000016  0.019007  219.7802
2       0.000074 -0.340319   47.9616
3       0.000088  0.678222  442.4779
4       0.000149 -0.905713  134.2282
...          ...       ...       ...
119611  6.273733  0.674210   16.9492
119612  6.282287  0.833606   16.7224
119613  6.282195 -0.769130   18.5185
119614  6.282501 -0.595366   12.8205
119615  0.009440 -0.753388    7.8003

[119614 rows x 3 columns]

converting the polar coordinates to rectangulare coordinates

In [8]:
rectCoor['x'] = np.cos(polarCoor['ra']) * np.cos(polarCoor['dec']) * polarCoor['r']
rectCoor['y'] = np.sin(polarCoor['ra']) * polarCoor['r']
rectCoor['z'] = np.cos(polarCoor['ra']) * np.sin(polarCoor['dec']) * polarCoor['r']

In [9]:
rectCoor # view the dataframe. note that the vectors are column vectors

                 x         y           z
id
0         0.000000  0.000000    0.000000
1       219.740502  0.003452    4.177065
2        45.210918  0.003553  -16.008996
3       344.552785  0.038807  277.614965
4        82.835512  0.019995 -105.619540
...            ...       ...         ...
119611   13.240129 -0.160206   10.580581
119612   11.240969 -0.015029   12.380591
119613   13.305832 -0.018336  -12.879803
119614   10.614641 -0.008774   -7.189891
119615    5.689091  0.073635   -5.336057

[119614 rows x 3 columns]

3. write out results, save the star catalog dataframe in a pickled file

In [10]:
astroTable.to_pickle('/home/user/pickle/astroTable_df.bin')
# we can specify as a named argument whether we want pandas
# to write out the index column. the default is to do so.
rectCoor.to_csv('/home/user/datafile/rectCoor.csv')

In [9]:
%whos

Variable     Type         Data/Info
-----------------------------------
astroTable   DataFrame            hip        hd  hr<...>119614 rows x 36 columns]
np           module       <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
pd           module       <module 'pandas' from '/h<...>ages/pandas/__init__.py'>
polarCoor    DataFrame                  ra       de<...>[119614 rows x 3 columns]
rectCoor     DataFrame                     x       <...>[119614 rows x 3 columns]

In [12]:
''' specifying a sample of records to extract using inequalities and logical operator &.
    the output is records of stars in a quadrant of the celestial sphere.
    df.loc[] allows you to select rows or columns by label or boolean array
'''
astroTable.loc[\
               (astroTable['ra'] >= 0) & (astroTable['ra'] <= 12) \
             & (astroTable['dec'] >= 0) & (astroTable['dec'] <= 90)\
             # statement split into multi-lines to enhance readability

,hip,hd,hr,gl,bf,proper,ra,dec,dist,pmra,pmdec,rv,mag,absmag,spect,ci,x,y,z,vx,vy,vz,rarad,decrad,pmrarad,pmdecrad,bayer,flam,con,comp,comp_primary,base,lum,var,var_min,var_max
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,NaN,NaN,NaN,NaN,NaN,Sol,0.000000,0.000000,0.0000,0.00,0.00,0.0,-26.70,4.850,G2V,0.656,0.000005,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,NaN,NaN,NaN,1,0,NaN,1.000000,NaN,NaN,NaN
7,7.0,NaN,NaN,NaN,NaN,NaN,0.001470,20.036114,57.8704,-208.12,-200.79,0.0,9.64,5.828,G0,0.740,54.367897,0.020886,19.827115,1.932000e-05,-0.000058,-0.000053,0.000385,0.349696,-1.008994e-06,-9.734574e-07,NaN,NaN,NaN,1,7,NaN,0.406256,NaN,NaN,NaN
9,9.0,224708.0,NaN,NaN,NaN,NaN,0.002355,36.585958,420.1681,-6.30,8.42,0.0,8.59,0.473,G5,1.067,337.379614,0.207994,250.431996,-1.021000e-05,-0.000013,0.000014,0.000617,0.638545,-3.054326e-08,4.082131e-08,NaN,NaN,NaN,1,9,NaN,56.337815,NaN,NaN,NaN
19,19.0,224721.0,NaN,NaN,NaN,NaN,0.003554,38.304050,249.3766,-2.50,-15.07,16.0,6.53,-0.454,G5,0.955,195.693966,0.182078,154.572309,2.414000e-05,-0.000003,-0.000004,0.000930,0.668532,-1.212034e-08,-7.306142e-08,NaN,NaN,NaN,1,19,NaN,132.312233,NaN,NaN,NaN
20,20.0,224723.0,NaN,NaN,NaN,NaN,0.004203,23.529228,96.6184,36.00,-22.98,0.0,8.51,3.585,G0,0.516,88.585158,0.097476,38.571692,4.280000e-06,0.000017,-0.000010,0.001100,0.410663,1.745329e-07,-1.114102e-07,NaN,NaN,NaN,1,20,NaN,3.206269,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118567,NaN,75404.0,NaN,NN 3516,NaN,NaN,8.850076,34.825106,23.2558,-52.17,-29.64,0.0,7.60,5.767,G0,NaN,-12.958998,14.018482,13.280767,3.020000e-06,0.000005,-0.000003,2.316945,0.607813,-2.529273e-07,-1.436794e-07,NaN,NaN,NaN,1,118567,NaN,0.429734,NaN,NaN,NaN
118586,NaN,NaN,NaN,Gl 332B,NaN,NaN,9.010887,41.783620,16.4312,-433.88,-248.49,0.0,6.18,5.102,G5 V,0.650,-8.687958,8.639195,10.948426,1.501000e-05,0.000034,-0.000015,2.359045,0.729262,-2.103510e-06,-1.204694e-06,NaN,NaN,NaN,2,44120,Gl 332,0.792866,NaN,NaN,NaN
118742,55203.0,98231.0,4375.0,Gl 423A,53Xi UMa,NaN,11.303118,31.528783,10.4167,-425.24,-581.01,-15.9,4.33,4.241,G0 Ve,0.590,-8.730890,1.610966,5.446747,2.430000e-06,0.000021,-0.000034,2.959149,0.550281,-2.061622e-06,-2.816821e-06,Xi,53.0,UMa,1,118742,Gl 423,1.752266,NaN,NaN,NaN
118743,NaN,98230.0,4374.0,Gl 423B,53Xi UMa,NaN,11.303118,31.528783,10.4167,-425.24,-581.01,-13.6,4.80,4.711,G0 Ve,NaN,-8.730989,1.610983,5.446808,4.600000e-07,0.000022,-0.000032,2.959149,0.550281,-2.061622e-06,-2.816821e-06,Xi,53.0,UMa,2,118742,Gl 423,1.136580,NaN,NaN,NaN
118759,NaN,NaN,NaN,Gl 431.1B,NaN,NaN,11.539406,61.083109,27.5179,-0.61,-70.00,0.0,7.10,4.902,G3 V,NaN,-13.209398,1.600598,24.087023,-8.100000e-06,0.000001,-0.000005,3.021010,1.066101,-2.957363e-09,-3.393550e-07,NaN,NaN,NaN,2,56121,Gl 431.1,0.953235,NaN,NaN,NaN